# Секретный токен Donation Alerts.
# Находится на Donation Alerts на странице "Настройки" -> "Основные настройки".
DonationAlertsToken:

# Никнеймы стримеров в игре
# Не забудьте про цветовые коды, если используете их
StreamersNamesList:
    - Evropejets
    - mdenz3

# Точные суммы донатов для событий
DonationAmounts:
    # Имя первого стримера (ДОЛЖЕН СОВПАДАТЬ С ПЕРВЫМ ЗНАЧЕНИЕМ, УКАЗАННЫМ В StreamersNamesList)
    Evropejets:
        # Насрать стримеру в инвентарь подписанными стаками говна
        ShitToInventory: 62
        # Выбить предмет из рук
        DropActiveItem: 65
        # Дать леща - толчок вперед, который отнимет 1 сердечко
        Lesch: 67
        # Дать хлеб в количестве N кусков
        GiveBread: 82
        # Выдать определенное количество алмазов (настраивается дальше)
        GiveDiamonds: 132
        # Заспавнятся несколько сотрудников НКВД, которые заходят увести вас в ГУЛАГ
        CallNKVD: 142
        # Дать очень смачный пинок под зад, который отнимет 1.5 сердечка
        PowerKick: 152
        # В вашем инвентаре будет случайным образом заменено N слотов (по умолчанию -5)
        # на некие предметы (по умолчанию - камни)
        RandomChange: 197
        # Заспавнить крипера за спиной
        SpawnCreeper: 202
        # Уничтожить вещи, выпавшие после последней смерти
        ClearLastDeathDrop: 214
        # Все прирученные игроком кошки снова станут дикими, а прирученные волки,
        # помимо этого, еще и нападут на игрока, который был их хозяином
        TamedBecomesEnemies: 252
        # Заспавнить исполинского Иосифа Сталина, испепеляющий все вокруг
        CallStalin: 352
        # Оставить игроку лишь полсердечка
        HalfHeart: 602
        # Через N секунд (по умолчанию - 3) произойдет взрыв с радиусом M
        # (по умолчанию - 20) вокруг игрока
        BigBoom: 2002
        # Выдать целый стак алмазов
        GiveStackOfDiamonds: 2012
    # Имя второго стримера (ДОЛЖЕН СОВПАДАТЬ СО ВТОРЫМ ЗНАЧЕНИЕМ, УКАЗАННЫМ В StreamersNamesList)
    mdenz3:
        # Насрать стримеру в инвентарь подписанными стаками говна
        ShitToInventory: 61
        # Выбить предмет из рук
        DropActiveItem: 64
        # Дать леща - толчок вперед, который отнимет 1 сердечко
        Lesch: 66
        # Дать хлеб в количестве N кусков
        GiveBread: 81
        # Выдать определенное количество алмазов (настраивается дальше)
        GiveDiamonds: 131
        # Заспавнятся несколько сотрудников НКВД, которые заходят увести вас в ГУЛАГ
        CallNKVD: 141
        # Дать очень смачный пинок под зад, который отнимет 1.5 сердечка
        PowerKick: 151
        # В вашем инвентаре будет случайным образом заменено N слотов (по умолчанию -5)
        # на некие предметы (по умолчанию - камни)
        RandomChange: 196
        # Заспавнить крипера за спиной
        SpawnCreeper: 201
        # Уничтожить вещи, выпавшие после последней смерти
        ClearLastDeathDrop: 213
        # Все прирученные игроком кошки снова станут дикими, а прирученные волки,
        # помимо этого, еще и нападут на игрока, который был их хозяином
        TamedBecomesEnemies: 251
        # Заспавнить исполинского Иосифа Сталина, испепеляющий все вокруг
        CallStalin: 351
        # Оставить игроку лишь полсердечка
        HalfHeart: 601
        # Через N секунд (по умолчанию - 3) произойдет взрыв с радиусом M
        # (по умолчанию - 20) вокруг игрока
        BigBoom: 2001
        # Выдать целый стак алмазов
        GiveStackOfDiamonds: 2011

# Сколько блоков говна игроки будут получать в инвентарь от ShitToInventory
DirtAmount: 10
# Сколько алмазов игроки будут получать в инвентарь от GiveDiamonds
DiamondsAmount: 4
# Сколько хлеба игроки будут получать в инвентарь от GiveBread
BreadAmount: 4
# Радиус взрыва от BigBoom
BigBoomRadius: 20

# Фильтр ников для твитча: true - вкл, false - выкл
TwitchFilter: true
# Блеклист субстрок для фильтра
BlacklistedSubstrings:
    - негр
    - пидо
    - пида
    - niga
    - нигр
    - ниге
    - додик
    - петух
    - петуч
    - куколд
    - симп
    - kukold
    - cuckold
    - fag
    - хуе
    - хуй
    - даун
    - кады
    - кадь
    - kadb
    - 4e4e
    - 4e4n
    - cheche
    - chechn
    - 4echn
    - che4n
    - 4eche
    - 4eche
# Вайтлист субстрок для фильтра
WhitelistedSubstrings:
    - книг
    - нигерия



